apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: "default-admin-${KUBE_NS}"
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: "admin"
subjects:
- kind: ServiceAccount
  name: default
  namespace: ${KUBE_NS}
