[[constraint]]
  name = "k8s.io/api"
  version = "kubernetes-1.8.2"

[[constraint]]
  name = "k8s.io/apiextensions-apiserver"
  version = "kubernetes-1.8.2"

[[constraint]]
  name = "k8s.io/apimachinery"
  version = "kubernetes-1.8.2"

[[constraint]]
  name = "k8s.io/client-go"
  version = "kubernetes-1.8.2"

[[constraint]]
  name = "github.com/coreos/etcd-operator"
  version = "v0.8.3"

[[constraint]]
  name = "github.com/sirupsen/logrus"
  version = "1.0.0"

[[constraint]]
  name = "github.com/hashicorp/vault"
  version = "v0.9.0"
