#!/usr/bin/env bash

set -o errexit
set -o nounset
set -o pipefail

function go_build {
	echo "building "${1}"..."
	if [ ! -z ${GOINSTALL+x} ] && [ "${GOINSTALL}" = "y" ]
	then
  		GOBIN=${bin_dir} GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go install ./cmd/${1}/
  		mv ${bin_dir}/${1} ${bin_dir}/${1}
	else
  		GOOS=linux GOARCH=amd64 CGO_ENABLED=0 go build -o ${bin_dir}/${1} ./cmd/${1}/
	fi
}

if ! which go > /dev/null; then
	echo "golang needs to be installed"
	exit 1
fi

bin_dir="$(pwd)/_output/bin"
mkdir -p ${bin_dir} || true

go_build vault-operator
